language: objective-c
script: xcodebuild -target Nodelike -arch armv7
install:
  - git submodule update --init --recursive
after_success:
  - brew install sloccount
  - sudo easy_install pip
  - sudo pip install coviolations_app
  - covio
