language: objective-c
script: xcodebuild -target "Node To Go" -sdk iphonesimulator
install:
  - gem install cocoapods
  - pod install
after_success:
  - brew install sloccount
  - sudo easy_install pip
  - sudo pip install coviolations_app
  - covio
