language: objective-c
script: xcodebuild -target Interpreter -arch armv7 -sdk iphonesimulator
install:
  - git submodule update --init --recursive
after_success:
  - brew install sloccount
  - sudo easy_install pip
  - sudo pip install coviolations_app
  - covio
