language: objective-c
xcode_sdk: iphonesimulator
xcode_scheme: Node
xcode_workspace: Interpreter.xcworkspace
rvm: 2.0.0
notifications:
  flowdock: 803358c5edc46b50866b8e588b4c374b
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fa1f3636231a3e89e7fd
    on_success: change
    on_failure: always
    on_start: false
  hipchat:
    secure: aWO9pLQ74SvlXTUMgXrIrezP5VQZdJE2gNgfmmOoK6S6qUiRALJi0wSF4njv1WFf9ZLWaWr8b7Z7Gs4ZeF+rhI7/xGw7YdQaJYkiQ/yo0QdUhn5NTgzJo8CMyremNJx/qcK0+FbwsttIpB7kYWW9XuFGUrmHGojX5Lx1pYnFbZk=
