language: objective-c
script: xcodebuild -sdk iphonesimulator -workspace Interpreter.xcworkspace -scheme "Node To Go"
install:
  - gem install cocoapods
  - pod install
after_success:
  - brew install sloccount
  - sudo easy_install pip
  - sudo pip install coviolations_app
  - covio
